# Ref: https://hub.docker.com/r/cytopia/ansible-lint
image: docker.io/cytopia/ansible-lint

stages:
  - linting

ansible-lint:
  stage: linting
  artifacts:
    when: always
    reports:
      junit: ansible-lint.xml
  script:
    - ansible-lint -v --show-relpath --parseable-severity --nocolor .
      | ansible-lint-junit -o ansible-lint.xml
