---
- name: Nextcloud Guide iet-182
  hosts: all
  become: true
  roles:
  - prep_os
  - mariadb
  # - prep_mariadb
  # - prep_php_fpm
  # - prep_nginx
  # - prep_ssl
  # - prep_redis
  # - prep_ssmtp
  # - prep_nextcloud
  