---
- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true
- name: install system packages
  apt:
    name:
    - zip
    - unzip
    - curl
    - software-properties-common
    - apt-transport-https
    state: latest